### ISSUE TITLE
I can publish the extension to Chrome (and give full credit)

### ISSUE THREAD

**Issue by Aljoberg** [MrQuackDuck/CorrectPause#3]
Hello, I've paid for the chrome extension developer account, since I published some random extension back in the day. Tampermonkey is kinda hard to set up for non technical users, so I _could_ publish your extension to chromium based browsers. (obviously not without your consent lol)
And this is not some kinda forced question or anything, I just liked the extension and it would be cool if it was on chromium, since most of the browsers are made from that. Thanks in advance!

**Comment by MrQuackDuck** [comment]
Thank you for that great proposition, I agree!
As stated above, you need to insert a link to the original extension Github
page, and also indicate my authorship.

When the extension will be published, notify me please.
I will put a link to your extension in the description of my extension.

You can contact me if you need anything else :)

**Comment by Aljoberg** [comment]
Contacted on telegram, so we don't spam this issue thread. Thanks!
