### ISSUE TITLE
Adding support for EMBED videos.

### ISSUE THREAD

**Issue by Konata123** [MrQuackDuck/CorrectPause#5]
Hi,

Is it possible to add support for embed videos? 

This type of links: 
https://www.youtube.com/embed/ftl3ZCr_Cn4

I started to use this script and I have problems in it with space button support:
https://greasyfork.org/pl/scripts/435669-redirect-yt-video-to-embedded-video

**Comment by MrQuackDuck** [comment]
Thank you for sharing a bug! Fixed in the new version, enjoy ❤

**Comment by Konata123** [comment]
Thanks for the quick response, but unfortunately it does not work properly. The spacebar stops working at all, only the pause symbol appears on the screen and the video continues playing. The K key works normally.

I'm using Chrome 122 + Ubuntu 20.04, if that makes any difference.

I use via Tampermonkey and add like this:

```
// ==UserScript==
// @name         YouTube: CorrectPause
// @version      1.7
// @description  Press spacebar to play/pause YouTube videos
// @author       MrQuackDuck
// @match        https://www.youtube.com/*
// @grant        none
// ==/UserScript==

<Here the contents of the correctPause.js file>
```

I did a test on a clean profile with only Tampermonkey and the script installed, but it doesn't improve anything.
I checked by installing also as an extension but there is no improvement.

**Comment by MrQuackDuck** [comment]
The Chrome version is being updated for a bit longer. You need to wait for a few days

**Comment by MrQuackDuck** [comment]
Also I noticed that in your TamperMonkey script you wrote `https://www.youtube.com/*`.
In order to fix this issue you need to write `https://www.youtube.com/watch*` to deny the script from working on embed videos. This will fix the issue.

**Comment by Konata123** [comment]
Sorry, but I think we misunderstood each other (forgive my English is not too good).

It's so far I have been using YT normally through type links:
https://www.youtube.com/watch?v=
And there were no problems with it, your script worked perfectly, when I turned on subtitles for example, the spacebar continued to work as pause/play.

But now I use a script that changes the address of the video automatically from "watch?v=" to "embed/". 
So I changed the address in Tampermonkey to "https://www.youtube.com/*", but after such a change on embed videos the spacebar stops working properly.
When there is a movie selected, the spacebar does not work at all.
When I turn on/click the subtitle button then the spacebar turns off/on subtitles but also pause/play video.

And I would like it to work on embed videos as it does on regular videos.

I don't know if this is the fault of my system (Ubuntu), I have no way to check on Windows. 
I checked on Firefox, but the version via Tampermonkey works the same as in Chrome. The version with "Firefox Browser Add-Ons" works on regular links and on embed it does not run.

**Comment by MrQuackDuck** [comment]
Oh, now I understand. I will fix it in the next version within a few days 👍

**Comment by Konata123** [comment]
There is no need to rush, the important thing is that you see if it can be fixed. Thank you.

**Comment by MrQuackDuck** [comment]
Fixed! Enjoy 🔥

**Comment by Konata123** [comment]
Thank you, it works almost perfectly. 
The spacebar started to work properly. However, when I turn on the subtitles the spacebar toggles them as well, but this can be survived because when I stop the movie I don't need the subtitles.
